CREATE TABLE "characters" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"saved_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text NOT NULL,
	"race" text NOT NULL,
	"race_variant" text,
	"class" text NOT NULL,
	"subclass" text NOT NULL,
	"level" integer NOT NULL,
	"background" text NOT NULL,
	"alignment" text NOT NULL,
	"hit_points" integer NOT NULL,
	"armor_class" integer NOT NULL,
	"armor_class_breakdown" text NOT NULL,
	"speed" text NOT NULL,
	"proficiency_bonus" integer NOT NULL,
	"spell_attack_bonus" integer,
	"spell_save_dc" integer,
	"backstory" text NOT NULL,
	"ability_scores" jsonb NOT NULL,
	"saving_throws" jsonb NOT NULL,
	"skills" jsonb NOT NULL,
	"proficiencies" jsonb NOT NULL,
	"weapons" jsonb,
	"equipment" jsonb NOT NULL,
	"features" jsonb NOT NULL,
	"spell_slots" jsonb,
	"spells" jsonb,
	"traits" jsonb NOT NULL
);
