export const RACES = [
  "Aarakocra",
  "Aasimar",
  "Bugbear",
  "Centaur",
  "Changeling",
  "Dragonborn",
  "Dwarf",
  "Elf",
  "Fairy",
  "Firbolg",
  "Genasi",
  "Githyanki",
  "Githzerai",
  "Gnome",
  "Goblin",
  "Goliath",
  "Half-Elf",
  "Half-Orc",
  "Halfling",
  "Harengon",
  "Hobgoblin",
  "Human",
  "Kenku",
  "Kobold",
  "Lizardfolk",
  "Minotaur",
  "Orc",
  "Owlin",
  "Satyr",
  "Shifter",
  "Tabaxi",
  "Tiefling",
  "Tortle",
  "Triton",
  "Yuan-ti",
] as const;

export const RACE_VARIANTS: Record<string, string[]> = {
  Dragonborn: ["Standard", "Chromatic", "Gem", "Metallic"],
  Dwarf: ["Hill Dwarf", "Mountain Dwarf", "Duergar"],
  Elf: [
    "Dark Elf (Drow)",
    "Eladrin",
    "High Elf",
    "Sea Elf",
    "Shadar-kai",
    "Wood Elf",
  ],
  Genasi: ["Air", "Earth", "Fire", "Water"],
  Gnome: ["Deep Gnome", "Forest Gnome", "Rock Gnome"],
  Halfling: ["Lightfoot", "Stout"],
  Human: ["Standard", "Variant"],
  Shifter: ["Beasthide", "Longtooth", "Swiftstride", "Wildhunt"],
};

export const CLASSES = [
  "Artificer",
  "Barbarian",
  "Bard",
  "Cleric",
  "Druid",
  "Fighter",
  "Monk",
  "Paladin",
  "Ranger",
  "Rogue",
  "Sorcerer",
  "Warlock",
  "Wizard",
] as const;

export const SUBCLASSES: Record<string, string[]> = {
  Artificer: ["Alchemist", "Armorer", "Artillerist", "Battle Smith"],
  Barbarian: [
    "Path of the Ancestral Guardian",
    "Path of the Battlerager",
    "Path of the Beast",
    "Path of the Berserker",
    "Path of the Storm Herald",
    "Path of the Totem Warrior",
    "Path of Wild Magic",
    "Path of the Zealot",
  ],
  Bard: [
    "College of Creation",
    "College of Eloquence",
    "College of Glamour",
    "College of Lore",
    "College of Swords",
    "College of Valor",
    "College of Whispers",
  ],
  Cleric: [
    "Arcana Domain",
    "Forge Domain",
    "Grave Domain",
    "Knowledge Domain",
    "Life Domain",
    "Light Domain",
    "Nature Domain",
    "Order Domain",
    "Peace Domain",
    "Tempest Domain",
    "Trickery Domain",
    "Twilight Domain",
    "War Domain",
  ],
  Druid: [
    "Circle of Dreams",
    "Circle of the Land",
    "Circle of the Moon",
    "Circle of the Shepherd",
    "Circle of Spores",
    "Circle of Stars",
    "Circle of Wildfire",
  ],
  Fighter: [
    "Arcane Archer",
    "Battle Master",
    "Cavalier",
    "Champion",
    "Eldritch Knight",
    "Psi Warrior",
    "Purple Dragon Knight",
    "Rune Knight",
    "Samurai",
  ],
  Monk: [
    "Way of the Ascendant Dragon",
    "Way of the Astral Self",
    "Way of the Drunken Master",
    "Way of the Four Elements",
    "Way of the Kensei",
    "Way of the Long Death",
    "Way of Mercy",
    "Way of the Open Hand",
    "Way of Shadow",
    "Way of the Sun Soul",
  ],
  Paladin: [
    "Oath of the Ancients",
    "Oath of Conquest",
    "Oath of the Crown",
    "Oath of Devotion",
    "Oath of Glory",
    "Oath of Redemption",
    "Oath of Vengeance",
    "Oath of the Watchers",
  ],
  Ranger: [
    "Beast Master",
    "Drakewarden",
    "Fey Wanderer",
    "Gloom Stalker",
    "Horizon Walker",
    "Hunter",
    "Monster Slayer",
    "Swarmkeeper",
  ],
  Rogue: [
    "Arcane Trickster",
    "Assassin",
    "Inquisitive",
    "Mastermind",
    "Phantom",
    "Scout",
    "Soulknife",
    "Swashbuckler",
    "Thief",
  ],
  Sorcerer: [
    "Aberrant Mind",
    "Clockwork Soul",
    "Divine Soul",
    "Draconic Bloodline",
    "Shadow Magic",
    "Storm Sorcery",
    "Wild Magic",
  ],
  Warlock: [
    "The Archfey",
    "The Celestial",
    "The Fathomless",
    "The Fiend",
    "The Genie",
    "The Great Old One",
    "The Hexblade",
    "The Undying",
  ],
  Wizard: [
    "Bladesinging",
    "Order of Scribes",
    "School of Abjuration",
    "School of Conjuration",
    "School of Divination",
    "School of Enchantment",
    "School of Evocation",
    "School of Illusion",
    "School of Necromancy",
    "School of Transmutation",
    "War Magic",
  ],
};

export const BACKGROUNDS = [
  "Acolyte",
  "Charlatan",
  "City Watch",
  "Clan Crafter",
  "Cloistered Scholar",
  "Courtier",
  "Criminal",
  "Entertainer",
  "Faction Agent",
  "Far Traveler",
  "Folk Hero",
  "Guild Artisan",
  "Haunted One",
  "Hermit",
  "Inheritor",
  "Knight of the Order",
  "Mercenary Veteran",
  "Noble",
  "Outlander",
  "Sage",
  "Sailor",
  "Soldier",
  "Urban Bounty Hunter",
  "Urchin",
  "Uthgardt Tribe Member",
  "Waterdhavian Noble",
] as const;

export const SPELLCASTING_ABILITY: Record<string, "int" | "wis" | "cha"> = {
  Artificer: "int",
  Bard: "cha",
  Cleric: "wis",
  Druid: "wis",
  Paladin: "cha",
  Ranger: "wis",
  Sorcerer: "cha",
  Warlock: "cha",
  Wizard: "int",
};

export const SUBCLASS_SPELLCASTING_ABILITY: Record<
  string,
  "int" | "wis" | "cha"
> = {
  "Eldritch Knight": "int",
  "Arcane Trickster": "int",
};

export const ALIGNMENTS = [
  "Lawful Good",
  "Neutral Good",
  "Chaotic Good",
  "Lawful Neutral",
  "True Neutral",
  "Chaotic Neutral",
  "Lawful Evil",
  "Neutral Evil",
  "Chaotic Evil",
] as const;
